DROP SCHEMA IF EXISTS ECommercePlatform;
CREATE SCHEMA ECommercePlatform;
USE ECommercePlatform;

CREATE TABLE Products (
    productID INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `description` TEXT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    category ENUM('Electronics', 'Clothing', 'Home & Kitchen', 
		'Books', 'Beauty & Personal Care', 'Toys & Games', 
		'Sports & Outdoors', 'Groceries', 'Health & Wellness', 
		'Automotive', 'Jewelry', 'Art & Crafts') 
        NOT NULL,
    quantityAvailable INT NOT NULL
);

CREATE TABLE Orders (
    orderID INT AUTO_INCREMENT PRIMARY KEY,
    orderDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    status ENUM('Processing', 'Out for Delivery', 'Delivered') DEFAULT 'Processing',
    grandTotal DECIMAL(10, 2) NOT NULL
);

CREATE TABLE OrderItems (
    orderItemID INT AUTO_INCREMENT PRIMARY KEY,
    orderID INT,
    productID INT,
    quantity INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    CONSTRAINT fk_OrderItems_orderID FOREIGN KEY (orderID) REFERENCES Orders(orderID),
    CONSTRAINT fk_OrderItems_productID FOREIGN KEY (productID) REFERENCES Products(productID)
);


-- Insert mock data for Products table
-- Generated By ChatGPT
INSERT INTO Products (`name`, `description`, price, category, quantityAvailable) 
VALUES 
('Smartphone', 'Latest model with high performance and sleek design', 799.99, 'Electronics', 50),
('Laptop', 'Lightweight laptop with high-speed processor', 1200.00, 'Electronics', 30),
('Coffee Maker', 'Automatic coffee machine with multiple settings', 150.00, 'Home & Kitchen', 20),
('T-shirt', 'Comfortable cotton T-shirt, various sizes', 25.99, 'Clothing', 100),
('Novel Book', 'Best-selling fiction book by renowned author', 19.99, 'Books', 200),
('Blender', 'Powerful blender for smoothies and shakes', 90.00, 'Home & Kitchen', 15),
('Headphones', 'Noise-cancelling headphones with high-quality sound', 199.99, 'Electronics', 40),
('Toy Car', 'Remote-controlled toy car for children', 35.00, 'Toys & Games', 60);

-- Insert mock data for Orders table
-- Generated By ChatGPT
INSERT INTO Orders (status, grandTotal) 
VALUES 
('Processing', 1199.99),
('Out for Delivery', 159.99),
('Delivered', 1400.00);

-- Insert mock data for OrderItems table
-- Generated By ChatGPT
INSERT INTO OrderItems (orderID, productID, quantity, price) 
VALUES 
(1, 1, 1, 799.99),  -- Order 1: Smartphone
(1, 2, 1, 1200.00),  -- Order 1: Laptop
(2, 3, 1, 150.00),   -- Order 2: Coffee Maker
(2, 4, 2, 25.99),    -- Order 2: 2 T-shirts
(3, 7, 1, 199.99),   -- Order 3: Headphones
(3, 8, 1, 35.00);    -- Order 3: Toy Car

-- Extended Sample Data for E-commerce Platform
-- Add more products across all categories
-- Generated by Claude

INSERT INTO Products (`name`, `description`, price, category, quantityAvailable) 
VALUES 
-- Electronics (10 more items)
('iPhone 15 Pro Max', 'Latest Apple smartphone with titanium design and A17 Pro chip', 1199.99, 'Electronics', 25),
('Samsung 65" QLED TV', '4K Smart TV with quantum dot technology and HDR support', 1299.00, 'Electronics', 12),
('MacBook Pro 16"', 'Professional laptop with M3 Max chip and 32GB RAM', 2499.00, 'Electronics', 8),
('iPad Air 11"', 'Versatile tablet with M2 chip and Apple Pencil support', 599.00, 'Electronics', 35),
('AirPods Pro 2nd Gen', 'Wireless earbuds with active noise cancellation', 249.00, 'Electronics', 75),
('Gaming Console PS5', 'Next-generation gaming console with 4K gaming capability', 499.99, 'Electronics', 20),
('Wireless Charger', 'Fast wireless charging pad compatible with multiple devices', 39.99, 'Electronics', 100),
('Bluetooth Speaker', 'Portable waterproof speaker with 360-degree sound', 89.99, 'Electronics', 45),
('Smart Watch', 'Fitness tracker with heart rate monitor and GPS', 299.00, 'Electronics', 60),
('4K Webcam', 'Ultra HD webcam for professional video calls and streaming', 179.99, 'Electronics', 30),

-- Clothing (15 items)
('Denim Jacket', 'Classic blue denim jacket with vintage wash', 79.99, 'Clothing', 40),
('Leather Boots', 'Genuine leather boots with waterproof coating', 159.99, 'Clothing', 25),
('Winter Coat', 'Insulated winter coat with faux fur hood', 199.99, 'Clothing', 18),
('Yoga Pants', 'Stretchy and comfortable yoga pants for active wear', 49.99, 'Clothing', 80),
('Dress Shirt', 'Formal cotton dress shirt in multiple colors', 59.99, 'Clothing', 65),
('Sneakers', 'Comfortable running sneakers with cushioned sole', 119.99, 'Clothing', 70),
('Summer Dress', 'Flowy summer dress perfect for warm weather', 69.99, 'Clothing', 45),
('Hoodie', 'Soft cotton hoodie with kangaroo pocket', 54.99, 'Clothing', 90),
('Chinos', 'Slim-fit chino pants in khaki and navy', 44.99, 'Clothing', 85),
('Polo Shirt', 'Classic polo shirt in various colors', 34.99, 'Clothing', 120),
('Cardigan', 'Cozy knit cardigan perfect for layering', 64.99, 'Clothing', 35),
('Sweatshirt', 'Comfortable crew neck sweatshirt', 39.99, 'Clothing', 75),
('Formal Dress', 'Elegant black dress for special occasions', 129.99, 'Clothing', 20),
('Swim Shorts', 'Quick-dry swim shorts with mesh lining', 29.99, 'Clothing', 60),
('Scarf', 'Soft cashmere scarf in multiple patterns', 49.99, 'Clothing', 55),

-- Home & Kitchen (12 items)
('Stand Mixer', 'Professional-grade stand mixer with multiple attachments', 299.99, 'Home & Kitchen', 15),
('Air Fryer', 'Compact air fryer for healthy cooking', 129.99, 'Home & Kitchen', 35),
('Vacuum Cleaner', 'Cordless stick vacuum with powerful suction', 249.99, 'Home & Kitchen', 20),
('Dining Table Set', '6-person dining table with matching chairs', 599.99, 'Home & Kitchen', 8),
('Cookware Set', '10-piece non-stick cookware set', 179.99, 'Home & Kitchen', 25),
('Memory Foam Mattress', 'Queen size memory foam mattress with cooling gel', 699.99, 'Home & Kitchen', 12),
('Food Processor', 'Multi-function food processor with various blades', 149.99, 'Home & Kitchen', 22),
('Throw Pillows', 'Decorative throw pillows set of 4', 39.99, 'Home & Kitchen', 80),
('Area Rug', 'Large area rug for living room decoration', 199.99, 'Home & Kitchen', 18),
('Knife Set', 'Professional kitchen knife set with wooden block', 129.99, 'Home & Kitchen', 30),
('Table Lamp', 'Modern LED table lamp with adjustable brightness', 79.99, 'Home & Kitchen', 45),
('Storage Containers', 'Glass food storage containers set of 12', 59.99, 'Home & Kitchen', 65),

-- Books (10 items)
('Programming Guide', 'Complete guide to modern web development', 49.99, 'Books', 150),
('Cooking Cookbook', 'International recipes from around the world', 34.99, 'Books', 200),
('Mystery Novel', 'Thrilling mystery novel by bestselling author', 24.99, 'Books', 300),
('Self-Help Book', 'Guide to personal development and success', 19.99, 'Books', 180),
('History Book', 'Comprehensive history of ancient civilizations', 39.99, 'Books', 120),
('Science Fiction', 'Epic space adventure trilogy collection', 59.99, 'Books', 90),
('Art Book', 'Beautiful collection of modern art masterpieces', 79.99, 'Books', 60),
('Biography', 'Inspiring biography of influential leader', 29.99, 'Books', 140),
('Travel Guide', 'Complete travel guide to European destinations', 44.99, 'Books', 85),
('Children\'s Book', 'Colorful illustrated book for young readers', 14.99, 'Books', 250),

-- Beauty & Personal Care (8 items)
('Skincare Set', 'Complete skincare routine with cleanser, toner, and moisturizer', 89.99, 'Beauty & Personal Care', 40),
('Hair Dryer', 'Professional ionic hair dryer with multiple heat settings', 119.99, 'Beauty & Personal Care', 25),
('Perfume', 'Luxury fragrance with floral and citrus notes', 79.99, 'Beauty & Personal Care', 60),
('Makeup Palette', 'Eyeshadow palette with 24 vibrant colors', 49.99, 'Beauty & Personal Care', 55),
('Electric Toothbrush', 'Sonic electric toothbrush with timer', 99.99, 'Beauty & Personal Care', 35),
('Body Lotion', 'Moisturizing body lotion with natural ingredients', 24.99, 'Beauty & Personal Care', 100),
('Shampoo & Conditioner', 'Sulfate-free shampoo and conditioner set', 34.99, 'Beauty & Personal Care', 80),
('Face Mask Set', 'Hydrating face masks pack of 10', 29.99, 'Beauty & Personal Care', 70),

-- Toys & Games (8 items)
('Board Game', 'Strategic board game for family fun', 39.99, 'Toys & Games', 45),
('LEGO Building Set', 'Creative building blocks set with 500 pieces', 69.99, 'Toys & Games', 30),
('Puzzle 1000 pieces', 'Challenging jigsaw puzzle with beautiful landscape', 19.99, 'Toys & Games', 85),
('Action Figure', 'Collectible superhero action figure', 24.99, 'Toys & Games', 65),
('Doll House', 'Wooden dollhouse with furniture included', 149.99, 'Toys & Games', 15),
('Video Game', 'Latest adventure video game for console', 59.99, 'Toys & Games', 50),
('Art Supplies', 'Complete art set with paints, brushes, and canvas', 44.99, 'Toys & Games', 40),
('Remote Control Drone', 'Mini drone with camera for aerial photography', 129.99, 'Toys & Games', 20),

-- Sports & Outdoors (10 items)
('Yoga Mat', 'Non-slip yoga mat with carrying strap', 34.99, 'Sports & Outdoors', 90),
('Camping Tent', '4-person waterproof camping tent', 199.99, 'Sports & Outdoors', 15),
('Bicycle', 'Mountain bike with 21-speed gear system', 599.99, 'Sports & Outdoors', 12),
('Fitness Tracker', 'Waterproof fitness band with heart rate monitor', 149.99, 'Sports & Outdoors', 40),
('Basketball', 'Official size basketball for indoor and outdoor play', 29.99, 'Sports & Outdoors', 75),
('Hiking Backpack', 'Durable hiking backpack with multiple compartments', 89.99, 'Sports & Outdoors', 25),
('Water Bottle', 'Insulated stainless steel water bottle', 24.99, 'Sports & Outdoors', 120),
('Tennis Racket', 'Professional tennis racket with grip tape', 119.99, 'Sports & Outdoors', 30),
('Dumbbells Set', 'Adjustable dumbbells set with rack', 299.99, 'Sports & Outdoors', 18),
('Sleeping Bag', 'Lightweight sleeping bag for camping', 79.99, 'Sports & Outdoors', 35),

-- Groceries (6 items)
('Organic Honey', 'Pure organic honey in glass jar', 12.99, 'Groceries', 200),
('Coffee Beans', 'Premium arabica coffee beans 2lb bag', 24.99, 'Groceries', 150),
('Olive Oil', 'Extra virgin olive oil 500ml bottle', 18.99, 'Groceries', 180),
('Protein Powder', 'Whey protein powder chocolate flavor', 39.99, 'Groceries', 85),
('Green Tea', 'Organic green tea bags pack of 100', 15.99, 'Groceries', 120),
('Nuts Mix', 'Mixed nuts trail mix 1lb bag', 19.99, 'Groceries', 95),

-- Health & Wellness (6 items)
('Vitamins', 'Daily multivitamin supplement 90 tablets', 29.99, 'Health & Wellness', 100),
('Essential Oils', 'Aromatherapy essential oils set of 6', 49.99, 'Health & Wellness', 60),
('Massage Gun', 'Percussive therapy massage device', 199.99, 'Health & Wellness', 25),
('Meditation Cushion', 'Comfortable meditation cushion with washable cover', 39.99, 'Health & Wellness', 45),
('First Aid Kit', 'Complete first aid kit for home and travel', 34.99, 'Health & Wellness', 70),
('Blood Pressure Monitor', 'Digital blood pressure monitor with app connectivity', 79.99, 'Health & Wellness', 35),

-- Automotive (5 items)
('Car Phone Mount', 'Magnetic car phone holder for dashboard', 19.99, 'Automotive', 150),
('Car Vacuum', 'Portable car vacuum cleaner with attachments', 59.99, 'Automotive', 40),
('Tire Pressure Gauge', 'Digital tire pressure gauge with LED display', 24.99, 'Automotive', 80),
('Car Seat Covers', 'Universal car seat covers set of 4', 79.99, 'Automotive', 50),
('Dash Camera', 'HD dash camera with night vision', 129.99, 'Automotive', 30),

-- Jewelry (5 items)
('Silver Necklace', 'Sterling silver chain necklace 18 inches', 89.99, 'Jewelry', 40),
('Wedding Ring', '14k gold wedding band with diamond', 599.99, 'Jewelry', 15),
('Watch', 'Classic analog watch with leather strap', 199.99, 'Jewelry', 25),
('Earrings', 'Pearl stud earrings with gold setting', 149.99, 'Jewelry', 35),
('Bracelet', 'Charm bracelet with customizable charms', 79.99, 'Jewelry', 50),

-- Art & Crafts (5 items)
('Acrylic Paint Set', 'Professional acrylic paint set with 36 colors', 49.99, 'Art & Crafts', 60),
('Knitting Kit', 'Complete knitting kit with yarn and needles', 34.99, 'Art & Crafts', 45),
('Scrapbook Kit', 'Scrapbooking supplies with papers and stickers', 29.99, 'Art & Crafts', 70),
('Pottery Wheel', 'Electric pottery wheel for ceramic making', 399.99, 'Art & Crafts', 8),
('Calligraphy Set', 'Calligraphy pen set with ink and practice paper', 24.99, 'Art & Crafts', 55);

-- Add more sample orders
INSERT INTO Orders (status, grandTotal) 
VALUES 
('Processing', 249.00),
('Delivered', 89.99),
('Out for Delivery', 599.99),
('Processing', 149.98),
('Delivered', 1299.00),
('Processing', 79.99),
('Delivered', 199.99),
('Out for Delivery', 299.99),
('Processing', 159.98),
('Delivered', 49.99);

-- Add corresponding order items
INSERT INTO OrderItems (orderID, productID, quantity, price) 
VALUES 
-- Order 4: AirPods Pro
(4, 13, 1, 249.00),

-- Order 5: Bluetooth Speaker
(5, 16, 1, 89.99),

-- Order 6: Dining Table Set
(6, 26, 1, 599.99),

-- Order 7: Two T-shirts
(7, 4, 2, 25.99),
(7, 23, 2, 49.99),

-- Order 8: Samsung TV
(8, 10, 1, 1299.00),

-- Order 9: Leather Boots
(9, 19, 1, 79.99),

-- Order 10: Winter Coat
(10, 20, 1, 199.99),

-- Order 11: Stand Mixer
(11, 25, 1, 299.99),

-- Order 12: Multiple small items
(12, 35, 1, 39.99),  -- Board Game
(12, 47, 1, 34.99),  -- Yoga Mat
(12, 55, 1, 24.99),  -- Coffee Beans
(12, 60, 2, 29.99),  -- Vitamins (2 bottles)

-- Order 13: Single book
(13, 31, 1, 49.99);  -- Programming Guide