DROP SCHEMA IF EXISTS ECommercePlatform;
CREATE SCHEMA ECommercePlatform;
USE ECommercePlatform;

CREATE TABLE Products (
    productID INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `description` TEXT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    category ENUM('Electronics', 'Clothing', 'Home & Kitchen', 
		'Books', 'Beauty & Personal Care', 'Toys & Games', 
		'Sports & Outdoors', 'Groceries', 'Health & Wellness', 
		'Automotive', 'Jewelry', 'Art & Crafts') 
        NOT NULL,
    quantityAvailable INT NOT NULL
);

CREATE TABLE Orders (
    orderID INT AUTO_INCREMENT PRIMARY KEY,
    orderDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    status ENUM('Processing', 'Out for Delivery', 'Delivered') NOT NULL,
    grandTotal DECIMAL(10, 2) NOT NULL
);

CREATE TABLE OrderItems (
    orderItemID INT AUTO_INCREMENT PRIMARY KEY,
    orderID INT,
    productID INT,
    quantity INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    CONSTRAINT fk_OrderItems_orderID FOREIGN KEY (orderID) REFERENCES Orders(orderID),
    CONSTRAINT fk_OrderItems_productID FOREIGN KEY (productID) REFERENCES Products(productID)
);


-- Insert mock data for Products table
-- Generated By ChatGPT
INSERT INTO Products (`name`, `description`, price, category, quantityAvailable) 
VALUES 
('Smartphone', 'Latest model with high performance and sleek design', 799.99, 'Electronics', 50),
('Laptop', 'Lightweight laptop with high-speed processor', 1200.00, 'Electronics', 30),
('Coffee Maker', 'Automatic coffee machine with multiple settings', 150.00, 'Home & Kitchen', 20),
('T-shirt', 'Comfortable cotton T-shirt, various sizes', 25.99, 'Clothing', 100),
('Novel Book', 'Best-selling fiction book by renowned author', 19.99, 'Books', 200),
('Blender', 'Powerful blender for smoothies and shakes', 90.00, 'Home & Kitchen', 15),
('Headphones', 'Noise-cancelling headphones with high-quality sound', 199.99, 'Electronics', 40),
('Toy Car', 'Remote-controlled toy car for children', 35.00, 'Toys & Games', 60);

-- Insert mock data for Orders table
-- Generated By ChatGPT
INSERT INTO Orders (status, grandTotal) 
VALUES 
('Processing', 1199.99),
('Out for Delivery', 159.99),
('Delivered', 1400.00);

-- Insert mock data for OrderItems table
-- Generated By ChatGPT
INSERT INTO OrderItems (orderID, productID, quantity, price) 
VALUES 
(1, 1, 1, 799.99),  -- Order 1: Smartphone
(1, 2, 1, 1200.00),  -- Order 1: Laptop
(2, 3, 1, 150.00),   -- Order 2: Coffee Maker
(2, 4, 2, 25.99),    -- Order 2: 2 T-shirts
(3, 7, 1, 199.99),   -- Order 3: Headphones
(3, 8, 1, 35.00);    -- Order 3: Toy Car